import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Suspense } from 'react'
import Loading from '@/components/loading'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>idc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-screen w-screen border-2 border-red-400'>
        <section className='m-auto  w-fit'>
          <Suspense fallback={<Loading />}>
            <video loop autoPlay muted playsInline>
              <source src='https://ryanidc.s3.ap-southeast-1.amazonaws.com/idc.mp4' type='video/mp4' />
              Your browser does not support the video tag.
            </video>
          </Suspense>
        </section>
      </div>
    </>
  )
}
